[project]
name = "seiws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "zeep>=4.2.1",
]

[project.scripts]
seiws = "seiws:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
