UNIDADES_BLOQUEIO = [
    {
        "IdUnidade": "110000966",
        "Sigla": "FIGF",
        "Descricao": "Gerência de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000973",
        "Sigla": "FISF",
        "Descricao": "Gerência de Suporte à Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000965",
        "Sigla": "SFI",
        "Descricao": "Superintendência de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
]

UNIDADES_INSTRUCAO = [
    {
        "IdUnidade": "110000996",
        "Sigla": "GR01",
        "Descricao": "Gerência Regional no Estado de São Paulo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001000",
        "Sigla": "GR01FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001001",
        "Sigla": "GR01FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001002",
        "Sigla": "GR01FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001003",
        "Sigla": "GR01FI4",
        "Descricao": "Processo de Fiscalização 4",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001007",
        "Sigla": "GR02",
        "Descricao": "Gerência Regional nos Estados do Rio de Janeiro e Espírito Santo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001011",
        "Sigla": "GR02FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001012",
        "Sigla": "GR02FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001013",
        "Sigla": "GR02FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001017",
        "Sigla": "GR03",
        "Descricao": "Gerência Regional nos Estados do Paraná e Santa Catarina",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001021",
        "Sigla": "GR03FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001022",
        "Sigla": "GR03FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001026",
        "Sigla": "GR04",
        "Descricao": "Gerência Regional no Estado de Minas Gerais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001030",
        "Sigla": "GR04FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001031",
        "Sigla": "GR04FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001032",
        "Sigla": "GR04FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001036",
        "Sigla": "GR05",
        "Descricao": "Gerência Regional no Estado do Rio Grande do Sul",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001040",
        "Sigla": "GR05FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001041",
        "Sigla": "GR05FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001045",
        "Sigla": "GR06",
        "Descricao": "Gerência Regional nos Estados de Pernambuco, Paraíba e Alagoas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001049",
        "Sigla": "GR06FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001050",
        "Sigla": "GR06FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001054",
        "Sigla": "GR07",
        "Descricao": "Gerência Regional nos Estados de Goiás, Mato Grosso, Mato Grosso do Sul e Tocantins",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001058",
        "Sigla": "GR07FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001059",
        "Sigla": "GR07FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001063",
        "Sigla": "GR08",
        "Descricao": "Gerência Regional nos Estados da Bahia e Sergipe",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001067",
        "Sigla": "GR08FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001068",
        "Sigla": "GR08FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001072",
        "Sigla": "GR09",
        "Descricao": "Gerência Regional nos Estados do Ceará, Rio Grande do Norte e Piauí",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001076",
        "Sigla": "GR09FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001077",
        "Sigla": "GR09FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001081",
        "Sigla": "GR10",
        "Descricao": "Gerência Regional nos Estados do Pará, Maranhão e Amapá",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001085",
        "Sigla": "GR10FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001086",
        "Sigla": "GR10FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001090",
        "Sigla": "GR11",
        "Descricao": "Gerência Regional nos Estados do Amazonas, Acre, Rondônia e Roraima",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001094",
        "Sigla": "GR11FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001095",
        "Sigla": "GR11FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001151",
        "Sigla": "UO001",
        "Descricao": "Unidade Operacional do Distrito Federal",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001154",
        "Sigla": "UO021",
        "Descricao": "Unidade Operacional no Estado do Espírito Santo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001155",
        "Sigla": "UO021FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001157",
        "Sigla": "UO031",
        "Descricao": "Unidade Operacional no Estado de Santa Catarina",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001158",
        "Sigla": "UO031FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001160",
        "Sigla": "UO061",
        "Descricao": "Unidade Operacional no Estado de Alagoas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001161",
        "Sigla": "UO062",
        "Descricao": "Unidade Operacional no Estado da Paraíba",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001162",
        "Sigla": "UO071",
        "Descricao": "Unidade Operacional no Estado de Mato Grosso",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001163",
        "Sigla": "UO072",
        "Descricao": "Unidade Operacional no Estado de Mato Grosso do Sul",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001164",
        "Sigla": "UO072FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001166",
        "Sigla": "UO073",
        "Descricao": "Unidade Operacional no Estado de Tocantins",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001167",
        "Sigla": "UO081",
        "Descricao": "Unidade Operacional no Estado de Sergipe",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001168",
        "Sigla": "UO091",
        "Descricao": "Unidade Operacional no Estado do Rio Grande do Norte",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001169",
        "Sigla": "UO092",
        "Descricao": "Unidade Operacional no Estado do Piauí",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001170",
        "Sigla": "UO101",
        "Descricao": "Unidade Operacional no Estado do Maranhão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001171",
        "Sigla": "UO102",
        "Descricao": "Unidade Operacional no Estado do Amapá",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001172",
        "Sigla": "UO111",
        "Descricao": "Unidade Operacional no Estado de Rondônia",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001173",
        "Sigla": "UO112",
        "Descricao": "Unidade Operacional no Estado do Acre",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001174",
        "Sigla": "UO113",
        "Descricao": "Unidade Operacional no Estado de Roraima",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
]

UNIDADES_FISCALIZA = [
    {
        "IdUnidade": "110001285",
        "Sigla": "AC",
        "Descricao": "Gabinete do Conselheiro Artur Coimbra de Oliveira",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001287",
        "Sigla": "AF",
        "Descricao": "Gabinete do Conselheiro Alexandre Reis Siqueira Freire",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000885",
        "Sigla": "AFCA",
        "Descricao": "Gerência de Aquisições e Contratos",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000886",
        "Sigla": "AFCA1",
        "Descricao": "Processo de Planejamento de Contratação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000887",
        "Sigla": "AFCA2",
        "Descricao": "Processo de Governança de Contratações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000888",
        "Sigla": "AFCA3",
        "Descricao": "Processo de Seleção de Fornecedores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000889",
        "Sigla": "AFCA4",
        "Descricao": "Processo de Alterações Contratuais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000890",
        "Sigla": "AFCA5",
        "Descricao": "Processo de Execução de Contratos",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000891",
        "Sigla": "AFCA6",
        "Descricao": "Processo de Prorrogações e Reajustes Contratuais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000892",
        "Sigla": "AFFO",
        "Descricao": "Gerência de Finanças, Orçamento e Arrecadação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000893",
        "Sigla": "AFFO1",
        "Descricao": "Processo de Orçamento",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000894",
        "Sigla": "AFFO2",
        "Descricao": "Processo de Execução Financeira",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000895",
        "Sigla": "AFFO3",
        "Descricao": "Processo de Contabilidade",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000896",
        "Sigla": "AFFO4",
        "Descricao": "Processo de Arrecadação e Cobrança",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000897",
        "Sigla": "AFFO5",
        "Descricao": "Processo de Acompanhamento e Avaliação da Arrecadação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000898",
        "Sigla": "AFFO6",
        "Descricao": "Processo de Processo Administrativo Fiscal",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000899",
        "Sigla": "AFIS",
        "Descricao": "Gerência de Infraestrutura, Serviços e Segurança Institucional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000900",
        "Sigla": "AFIS1",
        "Descricao": "Processo de Material e Patrimônio",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000904",
        "Sigla": "AFIS5",
        "Descricao": "Processo de Passagens e Transportes",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000905",
        "Sigla": "AFPE",
        "Descricao": "Gerência de Administração e Desenvolvimento de Pessoas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001278",
        "Sigla": "AFPE-BORA",
        "Descricao": "Oportunidades de Remanejamento",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001290",
        "Sigla": "AFPE-Concurso",
        "Descricao": "Comissão Organizadora do 6º Concurso Público da Anatel",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001259",
        "Sigla": "AFPE-TR",
        "Descricao": "Trânsito",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000906",
        "Sigla": "AFPE1",
        "Descricao": "Processo de Análise de Dados de Pessoal",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000907",
        "Sigla": "AFPE2",
        "Descricao": "Processo de Cadastro e Pagamento",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000908",
        "Sigla": "AFPE3",
        "Descricao": "Processo de Direito, Benefícios e Vantagens",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000909",
        "Sigla": "AFPE4",
        "Descricao": "Processo de Ingresso e Desligamento",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000910",
        "Sigla": "AFPE5",
        "Descricao": "Processo de Saúde",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000911",
        "Sigla": "AFPE6",
        "Descricao": "Processo de Capacitação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000912",
        "Sigla": "AFPE7",
        "Descricao": "Processo de Projetos e Inovações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000850",
        "Sigla": "AIN",
        "Descricao": "Assessoria Internacional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000855",
        "Sigla": "APC",
        "Descricao": "Assessoria Parlamentar e de Comunicação Social",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000856",
        "Sigla": "ARI",
        "Descricao": "Assessoria de Relações Institucionais",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000838",
        "Sigla": "ArquivoGeral.Sede",
        "Descricao": "Arquivo Geral da Sede",
        "SinProtocolo": "N",
        "SinArquivamento": "S",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000858",
        "Sigla": "ARU",
        "Descricao": "Assessoria de Relações com os Usuários",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000859",
        "Sigla": "ATC",
        "Descricao": "Assessoria Técnica",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000860",
        "Sigla": "AUD",
        "Descricao": "Auditoria Interna",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001279",
        "Sigla": "C-INT",
        "Descricao": "Comitê de Infraestrutura de Telecomunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001280",
        "Sigla": "CAD",
        "Descricao": "Comissão de Acompanhamento da Avaliação de Desempenho Institucional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001242",
        "Sigla": "CAED",
        "Descricao": "Comissão de Avaliação Especial de Desempenho",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001243",
        "Sigla": "CAI",
        "Descricao": "Comissão de Arbitragem em Interconexão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001241",
        "Sigla": "CAID",
        "Descricao": "Comissão de Avaliação Individual de Desempenho",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001244",
        "Sigla": "CAT",
        "Descricao": "Comissão de Assessoramento Técnico da CAI",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001235",
        "Sigla": "CBC1",
        "Descricao": "Comissão de Governança e Regimes Internacionais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001236",
        "Sigla": "CBC2",
        "Descricao": "Comissão de Radiocomunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001237",
        "Sigla": "CBC3",
        "Descricao": "Comissão de Normalização de Telecomunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001238",
        "Sigla": "CBC4",
        "Descricao": "Comissão de Desenvolvimento das Telecomunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000862",
        "Sigla": "CC",
        "Descricao": "Conselho Consultivo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001260",
        "Sigla": "CD",
        "Descricao": "Conselho Diretor",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001248",
        "Sigla": "CDUST",
        "Descricao": "Comitê de Defesa dos Usuários de Serviços de Telecomunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001240",
        "Sigla": "CEA",
        "Descricao": "Comissão de Ética da Anatel",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001251",
        "Sigla": "CEAD",
        "Descricao": "Comissão Especial de Avaliação do Programa de Gestão por Desempenho",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001256",
        "Sigla": "CEADI",
        "Descricao": "Centro de Altos Estudos em Comunicações Digitais e Inovações Tecnológicas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001245",
        "Sigla": "CEL.RF",
        "Descricao": "Comissão Especial de Licitação para Outorga de Uso de Radiofrequências",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001249",
        "Sigla": "CEO",
        "Descricao": "Comitê de Uso do Espectro e de Órbita",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001282",
        "Sigla": "CGE",
        "Descricao": "Comissão de Gestão Executiva",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001267",
        "Sigla": "CIG",
        "Descricao": "Comitê Interno de Governança",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001296",
        "Sigla": "CL",
        "Descricao": "Gabinete da Conselheira Cristiana Camarate Silveira Martins Leão Quinalia",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000914",
        "Sigla": "CODI",
        "Descricao": "Gerência de Controle de Obrigações de Direitos dos Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000923",
        "Sigla": "COGE",
        "Descricao": "Gerência de Controle de Obrigações Gerais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000932",
        "Sigla": "COQL",
        "Descricao": "Gerência de Controle de Obrigações de Qualidade",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000941",
        "Sigla": "COUN",
        "Descricao": "Gerência de Controle de Obrigações de Universalização e de Ampliação do Acesso",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000951",
        "Sigla": "CPAE",
        "Descricao": "Gerência de Acompanhamento Econômico da Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001254",
        "Sigla": "CPDI-PADOS",
        "Descricao": "Comissão Permanente de Distribuição e Instrução de PADOS",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000957",
        "Sigla": "CPOE",
        "Descricao": "Gerência de Acompanhamento Societário e da Ordem Econômica",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001255",
        "Sigla": "CPPP",
        "Descricao": "Comitê das Prestadoras de Pequeno Porte",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000961",
        "Sigla": "CPRP",
        "Descricao": "Gerência de Monitoramento das Relações entre Prestadoras",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001247",
        "Sigla": "CRCA",
        "Descricao": "Comissão de Resolução de Conflitos das Agências Reguladoras",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000861",
        "Sigla": "CRG",
        "Descricao": "Corregedoria",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001252",
        "Sigla": "CSIC",
        "Descricao": "Comissão de Segurança da Informação e Comunicações da Anatel",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000966",
        "Sigla": "FIGF",
        "Descricao": "Gerência de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000967",
        "Sigla": "FIGF1",
        "Descricao": "Processo de Planejamento de Fiscalização e Alinhamento Estratégico",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000968",
        "Sigla": "FIGF2",
        "Descricao": "Processo de Fiscalização de Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000969",
        "Sigla": "FIGF3",
        "Descricao": "Processo de Fiscalização de Aspectos Gerais da Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000970",
        "Sigla": "FIGF4",
        "Descricao": "Processo de Inteligência Regulatória, Inovação e Projetos Estratégicos",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000971",
        "Sigla": "FIGF5",
        "Descricao": "Processo de Fiscalização de Arrecadação de Tributos e de Aspectos Econômicos da Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000972",
        "Sigla": "FIGF6",
        "Descricao": "Processo de Governança",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000973",
        "Sigla": "FISF",
        "Descricao": "Gerência de Suporte à Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000974",
        "Sigla": "FISF1",
        "Descricao": "Processo de Normas e Padrões para Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000975",
        "Sigla": "FISF2",
        "Descricao": "Processo de Equipamentos para Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000976",
        "Sigla": "FISF3",
        "Descricao": "Processo de Sistemas de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000977",
        "Sigla": "FISF4",
        "Descricao": "Processo de Sistemas de Gestão da Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001268",
        "Sigla": "FISF5",
        "Descricao": "Processo de Gestão de Recursos de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001283",
        "Sigla": "GAISPI",
        "Descricao": "Grupo de Acompanhamento da Implantação das Soluções para os Problemas de Interferência na faixa de 3.625 a 3.700 MHz",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001284",
        "Sigla": "GAPE",
        "Descricao": "Grupo de Acompanhamento do Custeio à Projetos de Conectividade de Escolas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001234",
        "Sigla": "GC-CBC",
        "Descricao": "Grupo de Coordenação das Comissões Brasileiras de Comunicação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000978",
        "Sigla": "GIDS",
        "Descricao": "Gerência de Planejamento, Desenvolvimento e Segurança de Sistemas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000837",
        "Sigla": "GIIB",
        "Descricao": "Gerência de Informações e Biblioteca",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000990",
        "Sigla": "GIMR",
        "Descricao": "Gerência de Planejamento, Operação e Manutenção de Redes",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001269",
        "Sigla": "GIMR6",
        "Descricao": "Processo de Infraestrutura e Operações de TIC - Segurança",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000841",
        "Sigla": "GPR",
        "Descricao": "Gabinete da Presidência",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000996",
        "Sigla": "GR01",
        "Descricao": "Gerência Regional no Estado de São Paulo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000997",
        "Sigla": "GR01AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000998",
        "Sigla": "GR01AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000999",
        "Sigla": "GR01CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001000",
        "Sigla": "GR01FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001001",
        "Sigla": "GR01FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001002",
        "Sigla": "GR01FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001003",
        "Sigla": "GR01FI4",
        "Descricao": "Processo de Fiscalização 4",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001004",
        "Sigla": "GR01GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001005",
        "Sigla": "GR01OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001006",
        "Sigla": "GR01RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001007",
        "Sigla": "GR02",
        "Descricao": "Gerência Regional nos Estados do Rio de Janeiro e Espírito Santo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001008",
        "Sigla": "GR02AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001009",
        "Sigla": "GR02AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001010",
        "Sigla": "GR02CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001011",
        "Sigla": "GR02FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001012",
        "Sigla": "GR02FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001013",
        "Sigla": "GR02FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001014",
        "Sigla": "GR02GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001015",
        "Sigla": "GR02OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001016",
        "Sigla": "GR02RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001017",
        "Sigla": "GR03",
        "Descricao": "Gerência Regional nos Estados do Paraná e Santa Catarina",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001018",
        "Sigla": "GR03AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001019",
        "Sigla": "GR03AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001020",
        "Sigla": "GR03CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001021",
        "Sigla": "GR03FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001022",
        "Sigla": "GR03FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001023",
        "Sigla": "GR03GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001024",
        "Sigla": "GR03OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001025",
        "Sigla": "GR03RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001026",
        "Sigla": "GR04",
        "Descricao": "Gerência Regional no Estado de Minas Gerais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001027",
        "Sigla": "GR04AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001028",
        "Sigla": "GR04AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001029",
        "Sigla": "GR04CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001030",
        "Sigla": "GR04FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001031",
        "Sigla": "GR04FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001032",
        "Sigla": "GR04FI3",
        "Descricao": "Processo de Fiscalização 3",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001033",
        "Sigla": "GR04GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001034",
        "Sigla": "GR04OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001035",
        "Sigla": "GR04RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001036",
        "Sigla": "GR05",
        "Descricao": "Gerência Regional no Estado do Rio Grande do Sul",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001037",
        "Sigla": "GR05AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001038",
        "Sigla": "GR05AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001039",
        "Sigla": "GR05CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001040",
        "Sigla": "GR05FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001041",
        "Sigla": "GR05FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001042",
        "Sigla": "GR05GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001043",
        "Sigla": "GR05OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001044",
        "Sigla": "GR05RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001045",
        "Sigla": "GR06",
        "Descricao": "Gerência Regional nos Estados de Pernambuco, Paraíba e Alagoas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001046",
        "Sigla": "GR06AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001047",
        "Sigla": "GR06AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001048",
        "Sigla": "GR06CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001049",
        "Sigla": "GR06FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001050",
        "Sigla": "GR06FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001051",
        "Sigla": "GR06GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001052",
        "Sigla": "GR06OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001053",
        "Sigla": "GR06RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001054",
        "Sigla": "GR07",
        "Descricao": "Gerência Regional nos Estados de Goiás, Mato Grosso, Mato Grosso do Sul e Tocantins",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001055",
        "Sigla": "GR07AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001056",
        "Sigla": "GR07AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001057",
        "Sigla": "GR07CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001058",
        "Sigla": "GR07FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001059",
        "Sigla": "GR07FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001060",
        "Sigla": "GR07GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001061",
        "Sigla": "GR07OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001062",
        "Sigla": "GR07RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001063",
        "Sigla": "GR08",
        "Descricao": "Gerência Regional nos Estados da Bahia e Sergipe",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001064",
        "Sigla": "GR08AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001065",
        "Sigla": "GR08AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001066",
        "Sigla": "GR08CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001067",
        "Sigla": "GR08FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001068",
        "Sigla": "GR08FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001069",
        "Sigla": "GR08GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001070",
        "Sigla": "GR08OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001071",
        "Sigla": "GR08RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001072",
        "Sigla": "GR09",
        "Descricao": "Gerência Regional nos Estados do Ceará, Rio Grande do Norte e Piauí",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001073",
        "Sigla": "GR09AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001074",
        "Sigla": "GR09AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001075",
        "Sigla": "GR09CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001076",
        "Sigla": "GR09FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001077",
        "Sigla": "GR09FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001078",
        "Sigla": "GR09GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001079",
        "Sigla": "GR09OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001080",
        "Sigla": "GR09RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001081",
        "Sigla": "GR10",
        "Descricao": "Gerência Regional nos Estados do Pará, Maranhão e Amapá",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001082",
        "Sigla": "GR10AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001083",
        "Sigla": "GR10AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001084",
        "Sigla": "GR10CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001085",
        "Sigla": "GR10FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001086",
        "Sigla": "GR10FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001087",
        "Sigla": "GR10GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001088",
        "Sigla": "GR10OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001089",
        "Sigla": "GR10RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001090",
        "Sigla": "GR11",
        "Descricao": "Gerência Regional nos Estados do Amazonas, Acre, Rondônia e Roraima",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001091",
        "Sigla": "GR11AF",
        "Descricao": "Processo de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001092",
        "Sigla": "GR11AT",
        "Descricao": "Assessoria Técnica da Gerência Regional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001093",
        "Sigla": "GR11CO",
        "Descricao": "Processo de Apuração de Descumprimento de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001094",
        "Sigla": "GR11FI1",
        "Descricao": "Processo de Fiscalização 1",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001095",
        "Sigla": "GR11FI2",
        "Descricao": "Processo de Fiscalização 2",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001096",
        "Sigla": "GR11GI",
        "Descricao": "Processo de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001097",
        "Sigla": "GR11OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001098",
        "Sigla": "GR11RC",
        "Descricao": "Processo de Relacionamento com os Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001281",
        "Sigla": "GT-Ciber",
        "Descricao": "Grupo Técnico de Segurança Cibernética e Gestão de Riscos de Infraestrutura Crítica",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001288",
        "Sigla": "GT-RCOM",
        "Descricao": "Grupo de Trabalho de Redes Comunitárias",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001239",
        "Sigla": "MCOM.Protocolo",
        "Descricao": "Protocolo do Ministério das Comunicações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001295",
        "Sigla": "NP",
        "Descricao": "Gabinete do Conselheiro Nilo Pasquali",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001100",
        "Sigla": "ORCN",
        "Descricao": "Gerência de Certificação e Numeração",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001105",
        "Sigla": "ORER",
        "Descricao": "Gerência de Espectro, Órbita e Radiodifusão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001106",
        "Sigla": "ORER1",
        "Descricao": "Processo de Exploração de Satélites",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001107",
        "Sigla": "ORER2",
        "Descricao": "Processo de Sistemas e Modelos de Gestão da Radiodifusão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001108",
        "Sigla": "ORER3",
        "Descricao": "Processo de Administração de Planos Básicos de Radiodifusão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001109",
        "Sigla": "ORER4",
        "Descricao": "Processo de Engenharia do Espectro",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001110",
        "Sigla": "ORER5",
        "Descricao": "Processo de Planejamento do Espectro",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001111",
        "Sigla": "ORER6",
        "Descricao": "Processo de Espectro Futuro e Internacional",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001112",
        "Sigla": "ORER7",
        "Descricao": "Processo de Integração Órbita e Espectro",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001113",
        "Sigla": "ORLE",
        "Descricao": "Gerência de Outorga e Licenciamento de Estações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001121",
        "Sigla": "ORLE8",
        "Descricao": "Processo  de Gestão e Administração",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000863",
        "Sigla": "OV",
        "Descricao": "Ouvidoria",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "S",
    },
    {
        "IdUnidade": "110001297",
        "Sigla": "Pessoal",
        "Descricao": "Pessoal do Gustavo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000867",
        "Sigla": "PFE",
        "Descricao": "Procuradoria Federal Especializada junto à Anatel",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000876",
        "Sigla": "PFE-AT",
        "Descricao": "Assessoria Técnica",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000877",
        "Sigla": "PFE-CA",
        "Descricao": "Processo de Contencioso Administrativo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000878",
        "Sigla": "PFE-CO",
        "Descricao": "Processo de Contencioso Judicial",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000879",
        "Sigla": "PFE-DA",
        "Descricao": "Divisão de Gestão Administrativa",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000880",
        "Sigla": "PFE-PA",
        "Descricao": "Processo de Procedimentos Administrativos",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000881",
        "Sigla": "PFE-PF",
        "Descricao": "Processo de Procedimentos Fiscais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000882",
        "Sigla": "PFE-PR",
        "Descricao": "Processo de Procedimentos Regulatórios",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000869",
        "Sigla": "PFE02",
        "Descricao": "Unidade Regional da 2ª Região da PFE-Anatel (RJ)",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000872",
        "Sigla": "PFE07",
        "Descricao": "Unidade Regional da 7ª Região da PFE-Anatel (GO)",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000873",
        "Sigla": "PFE08",
        "Descricao": "Unidade Regional da 8ª Região da PFE-Anatel (AL)",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000840",
        "Sigla": "PR",
        "Descricao": "Presidência Executiva",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001229",
        "Sigla": "Protocolo.AC",
        "Descricao": "Protocolo do Acre",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001197",
        "Sigla": "Protocolo.AL",
        "Descricao": "Protocolo de Alagoas",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001225",
        "Sigla": "Protocolo.AM",
        "Descricao": "Protocolo do Amazonas",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001223",
        "Sigla": "Protocolo.AP",
        "Descricao": "Protocolo do Amapá",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001209",
        "Sigla": "Protocolo.BA",
        "Descricao": "Protocolo da Bahia",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001145",
        "Sigla": "Protocolo.Callcenter",
        "Descricao": "Protocolo do Callcenter",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001213",
        "Sigla": "Protocolo.CE",
        "Descricao": "Protocolo do Ceará",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001185",
        "Sigla": "Protocolo.ES",
        "Descricao": "Protocolo do Espírito Santo",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001201",
        "Sigla": "Protocolo.GO",
        "Descricao": "Protocolo de Goiás",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001221",
        "Sigla": "Protocolo.MA",
        "Descricao": "Protocolo do Maranhão",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001191",
        "Sigla": "Protocolo.MG",
        "Descricao": "Protocolo de Minas Gerais",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001205",
        "Sigla": "Protocolo.MS",
        "Descricao": "Protocolo de Mato Grosso do Sul",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001203",
        "Sigla": "Protocolo.MT",
        "Descricao": "Protocolo de Mato Grosso",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001219",
        "Sigla": "Protocolo.PA",
        "Descricao": "Protocolo do Pará",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001199",
        "Sigla": "Protocolo.PB",
        "Descricao": "Protocolo da Paraíba",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001195",
        "Sigla": "Protocolo.PE",
        "Descricao": "Protocolo de Pernambuco",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001217",
        "Sigla": "Protocolo.PI",
        "Descricao": "Protocolo do Piauí",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001187",
        "Sigla": "Protocolo.PR",
        "Descricao": "Protocolo do Paraná",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001183",
        "Sigla": "Protocolo.RJ",
        "Descricao": "Protocolo do Rio de Janeiro",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001215",
        "Sigla": "Protocolo.RN",
        "Descricao": "Protocolo do Rio Grande do Norte",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001227",
        "Sigla": "Protocolo.RO",
        "Descricao": "Protocolo de Rondônia",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001231",
        "Sigla": "Protocolo.RR",
        "Descricao": "Protocolo de Roraima",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001193",
        "Sigla": "Protocolo.RS",
        "Descricao": "Protocolo do Rio Grande do Sul",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001189",
        "Sigla": "Protocolo.SC",
        "Descricao": "Protocolo de Santa Catarina",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001211",
        "Sigla": "Protocolo.SE",
        "Descricao": "Protocolo de Sergipe",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000839",
        "Sigla": "Protocolo.Sede",
        "Descricao": "Protocolo da Sede",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001181",
        "Sigla": "Protocolo.SP",
        "Descricao": "Protocolo de São Paulo",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001207",
        "Sigla": "Protocolo.TO",
        "Descricao": "Protocolo de Tocantins",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001124",
        "Sigla": "PRPE",
        "Descricao": "Gerência de Planejamento Estratégico",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001128",
        "Sigla": "PRRE",
        "Descricao": "Gerência de Regulamentação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001134",
        "Sigla": "PRUV",
        "Descricao": "Gerência de Universalização e Ampliação do Acesso",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001139",
        "Sigla": "RCIC",
        "Descricao": "Gerência de Interações Institucionais, Satisfação e Educação para o Consumo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001140",
        "Sigla": "RCIC1",
        "Descricao": "Processo de Interações Institucionais",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001141",
        "Sigla": "RCIC2",
        "Descricao": "Processo de Satisfação para o Consumo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001142",
        "Sigla": "RCIC3",
        "Descricao": "Processo de Educação para o Consumo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001143",
        "Sigla": "RCRC",
        "Descricao": "Gerência de Canais de Relacionamento com os Consumidores",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001147",
        "Sigla": "RCTS",
        "Descricao": "Gerência de Tratamento de Solicitações de Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000884",
        "Sigla": "SAF",
        "Descricao": "Superintendência de Administração e Finanças",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000842",
        "Sigla": "SCD",
        "Descricao": "Secretaria do Conselho Diretor",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000913",
        "Sigla": "SCO",
        "Descricao": "Superintendência de Controle de Obrigações",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000950",
        "Sigla": "SCP",
        "Descricao": "Superintendência de Competição",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000965",
        "Sigla": "SFI",
        "Descricao": "Superintendência de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000836",
        "Sigla": "SGI",
        "Descricao": "Superintendência de Gestão Interna da Informação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001099",
        "Sigla": "SOR",
        "Descricao": "Superintendência de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001123",
        "Sigla": "SPR",
        "Descricao": "Superintendência de Planejamento e Regulamentação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001138",
        "Sigla": "SRC",
        "Descricao": "Superintendência de Relações com Consumidores",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000883",
        "Sigla": "SUE",
        "Descricao": "Superintendente Executivo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110000834",
        "Sigla": "TESTE",
        "Descricao": "Unidade de Teste",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001289",
        "Sigla": "Tramita.GOV.BR",
        "Descricao": "Processo recebido via Tramita.GOV.BR",
        "SinProtocolo": "S",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001292",
        "Sigla": "Unidade_Teste_1",
        "Descricao": "Descrição Unidade de Teste 1 do segundo Órgão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001293",
        "Sigla": "Unidade_Teste_2",
        "Descricao": "Descrição Unidade de Teste 2 do segundo Órgão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001294",
        "Sigla": "Unidade_Teste_3",
        "Descricao": "Descrição Unidade de Teste 3 do segundo Órgão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001151",
        "Sigla": "UO001",
        "Descricao": "Unidade Operacional do Distrito Federal",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001154",
        "Sigla": "UO021",
        "Descricao": "Unidade Operacional no Estado do Espírito Santo",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001155",
        "Sigla": "UO021FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001157",
        "Sigla": "UO031",
        "Descricao": "Unidade Operacional no Estado de Santa Catarina",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001158",
        "Sigla": "UO031FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001159",
        "Sigla": "UO031OR",
        "Descricao": "Processo de Outorga",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001160",
        "Sigla": "UO061",
        "Descricao": "Unidade Operacional no Estado de Alagoas",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001161",
        "Sigla": "UO062",
        "Descricao": "Unidade Operacional no Estado da Paraíba",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001162",
        "Sigla": "UO071",
        "Descricao": "Unidade Operacional no Estado de Mato Grosso",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001163",
        "Sigla": "UO072",
        "Descricao": "Unidade Operacional no Estado de Mato Grosso do Sul",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001164",
        "Sigla": "UO072FI",
        "Descricao": "Processo de Fiscalização",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001165",
        "Sigla": "UO072OR",
        "Descricao": "Processo de Outorga e Recursos à Prestação",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001166",
        "Sigla": "UO073",
        "Descricao": "Unidade Operacional no Estado de Tocantins",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001167",
        "Sigla": "UO081",
        "Descricao": "Unidade Operacional no Estado de Sergipe",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001168",
        "Sigla": "UO091",
        "Descricao": "Unidade Operacional no Estado do Rio Grande do Norte",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001169",
        "Sigla": "UO092",
        "Descricao": "Unidade Operacional no Estado do Piauí",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001170",
        "Sigla": "UO101",
        "Descricao": "Unidade Operacional no Estado do Maranhão",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001171",
        "Sigla": "UO102",
        "Descricao": "Unidade Operacional no Estado do Amapá",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001172",
        "Sigla": "UO111",
        "Descricao": "Unidade Operacional no Estado de Rondônia",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001173",
        "Sigla": "UO112",
        "Descricao": "Unidade Operacional no Estado do Acre",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001174",
        "Sigla": "UO113",
        "Descricao": "Unidade Operacional no Estado de Roraima",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
    {
        "IdUnidade": "110001258",
        "Sigla": "VA",
        "Descricao": "Gabinete do Conselheiro Vicente Bandeira de Aquino Neto",
        "SinProtocolo": "N",
        "SinArquivamento": "N",
        "SinOuvidoria": "N",
    },
]

USUARIOS = [
    {
        "IdUsuario": "100003241",
        "Sigla": "alexander.estagio",
        "Nome": "Alexander Costa Brandao",
    },
    {
        "IdUsuario": "100003546",
        "Sigla": "ricciardi.estagio",
        "Nome": "Ana Luiza Mendonça Ricciardi",
    },
    {
        "IdUsuario": "100003098",
        "Sigla": "andersong.colab",
        "Nome": "Anderson da Silva Guedes",
    },
    {"IdUsuario": "100000141", "Sigla": "ane.meireles", "Nome": "Ane Meireles Martins"},
    {"IdUsuario": "100003387", "Sigla": "adlla.colab", "Nome": "Adlla Cruz de Moraes"},
    {
        "IdUsuario": "100000205",
        "Sigla": "brennom",
        "Nome": "Brenno Pires Andrade Maranhão",
    },
    {
        "IdUsuario": "100000214",
        "Sigla": "camilla.araujo",
        "Nome": "Camilla Fonseca Araújo",
    },
    {
        "IdUsuario": "100000217",
        "Sigla": "carla.barreto",
        "Nome": "Carla Barreto Faria Pereira",
    },
    {"IdUsuario": "100000079", "Sigla": "carlos.cesar", "Nome": "Carlos Cesar Lanzoni"},
    {
        "IdUsuario": "100000331",
        "Sigla": "cristinamg",
        "Nome": "Cristina de Miranda Gomes",
    },
    {
        "IdUsuario": "100003540",
        "Sigla": "contreira.estagio",
        "Nome": "Daniel Alexandro Contreira Junior",
    },
    {
        "IdUsuario": "100000375",
        "Sigla": "davila",
        "Nome": "David Sidney dos Santos Avila",
    },
    {
        "IdUsuario": "100003367",
        "Sigla": "davie.estagio",
        "Nome": "Davi Emanuel Silva Monteiro",
    },
    {"IdUsuario": "100000394", "Sigla": "diosnely", "Nome": "Diosnely Almeida de Lima"},
    {"IdUsuario": "100001689", "Sigla": "eliete", "Nome": "Eliete Rodrigues Paulino"},
    {"IdUsuario": "100000462", "Sigla": "elson", "Nome": "Elson José da Silva"},
    {
        "IdUsuario": "100000472",
        "Sigla": "enilsio",
        "Nome": "Enilsio Pereira Luiz Filho",
    },
    {"IdUsuario": "100000474", "Sigla": "eric", "Nome": "Eric Magalhães Delgado"},
    {
        "IdUsuario": "100000497",
        "Sigla": "fabiolago",
        "Nome": "Fábio Alexandre Oliveira Lago",
    },
    {
        "IdUsuario": "100003267",
        "Sigla": "felipef.estagio",
        "Nome": "Felipe Fabre Figueiredo",
    },
    {
        "IdUsuario": "100003564",
        "Sigla": "gabrielg.colab",
        "Nome": "Gabriel Glauber Neves de Campos",
    },
    {
        "IdUsuario": "100000585",
        "Sigla": "gianluca",
        "Nome": "Gianluca Rangearo Fiorentini",
    },
    {
        "IdUsuario": "100003408",
        "Sigla": "guilhermeb.estagio",
        "Nome": "Guilherme Braga Pinto",
    },
    {
        "IdUsuario": "100003248",
        "Sigla": "gustavos.colab",
        "Nome": "Gustavo Lustosa Camelo da Silva",
    },
    {"IdUsuario": "100000641", "Sigla": "hermano", "Nome": "Hermano Barros Tercius"},
    {
        "IdUsuario": "100002806",
        "Sigla": "jhonny.colab",
        "Nome": "Johnny Matos de Souza",
    },
    {"IdUsuario": "100003137", "Sigla": "jon.farinha", "Nome": "Jon Grisman Farinha"},
    {"IdUsuario": "100000737", "Sigla": "jordan", "Nome": "Jordan Silva de Paiva"},
    {"IdUsuario": "100000745", "Sigla": "jafonso", "Nome": "José Afonso Cosmo Junior"},
    {
        "IdUsuario": "100003285",
        "Sigla": "julianag.estagio",
        "Nome": "Juliana Garconi dos Santos",
    },
    {
        "IdUsuario": "100000817",
        "Sigla": "katiapalma",
        "Nome": "Katia Lilian Palma Barbosa",
    },
    {
        "IdUsuario": "100002792",
        "Sigla": "lidian.colab",
        "Nome": "Lidian de Alcântara Dias",
    },
    {
        "IdUsuario": "100002815",
        "Sigla": "loiane.colab",
        "Nome": "Loiane da Costa Silva",
    },
    {"IdUsuario": "100003222", "Sigla": "carvalho.estagio", "Nome": "Lucas Carvalho"},
    {
        "IdUsuario": "100003401",
        "Sigla": "luciene.colab",
        "Nome": "Luciene Ferreira de Sousa",
    },
    {
        "IdUsuario": "100003215",
        "Sigla": "luizf.estagio",
        "Nome": "Luiz Felipe Folha Tavares",
    },
    {
        "IdUsuario": "100001719",
        "Sigla": "marcelo.alves",
        "Nome": "Marcelo Alves da Silva",
    },
    {
        "IdUsuario": "100003534",
        "Sigla": "mariaaugusta",
        "Nome": "Maria Augusta Bretas Lima",
    },
    {"IdUsuario": "100001076", "Sigla": "marinajurua", "Nome": "Marina Machado Juruá"},
    {"IdUsuario": "100001089", "Sigla": "mauriciop", "Nome": "Mauricio Peroni"},
    {
        "IdUsuario": "100003247",
        "Sigla": "michaelr.colab",
        "Nome": "Michael Henrique de Souza da Rocha",
    },
    {"IdUsuario": "100001132", "Sigla": "odiley", "Nome": "Odiley Araújo Borges"},
    {"IdUsuario": "100001201", "Sigla": "rfaria", "Nome": "Rafael Faria Pinheiro"},
    {"IdUsuario": "100003260", "Sigla": "rodrigogebrim", "Nome": "Rodrigo Cruz Gebrim"},
    {
        "IdUsuario": "100001292",
        "Sigla": "rodrigomatos",
        "Nome": "Rodrigo Matos da Costa",
    },
    {
        "IdUsuario": "100003429",
        "Sigla": "rosanas.colab",
        "Nome": "Rosana Alves de Souza",
    },
    {
        "IdUsuario": "100003409",
        "Sigla": "sabino.colab",
        "Nome": "Willian Christian da Rocha Sabino",
    },
    {
        "IdUsuario": "100001366",
        "Sigla": "sergiow",
        "Nome": "Sergio Henrique Dias Weiler",
    },
    {
        "IdUsuario": "100001419",
        "Sigla": "tbotelho",
        "Nome": "Thiago Cardoso Henriques Botelho",
    },
    {"IdUsuario": "100001420", "Sigla": "thiago", "Nome": "Thiago da Gama"},
    {
        "IdUsuario": "100001426",
        "Sigla": "thyagobraun",
        "Nome": "Thyago de Oliveira Braun Guimarães",
    },
]
